# Generated by Django 5.1.1 on 2024-09-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="Not categorized")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="Unknown")),
                (
                    "rating",
                    models.PositiveBigIntegerField(
                        blank=True,
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("In stock", "In stock"),
                            ("Low in stock", "Low in stock"),
                            ("Out of stock", "Out of stock"),
                        ],
                        default="Out of stock",
                        max_length=30,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="book.bookcategory",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="check_stock_non_negative",
                    )
                ],
            },
        ),
    ]
